apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: elasticsearch:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/openshift-alpine-elasticsearch.git
      ref: release
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
    - github:
        secret: 3F4D4EE5-3945-45F8-8E5D-C788AED6BB9E
      type: GitHub
    - generic:
        secret: 3F4D4EE5-3945-45F8-8E5D-C788AED6BB9E
      type: Generic
    - type: ConfigChange
