apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: hhvm-webserver
  name: hhvm-webserver
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hhvm-webserver:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/openshift-hhvm.git
      ref: release
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
    - github:
        secret: X9Lb84hZqX6I77ZW2iWFHBhwvMstjNWJL
      type: GitHub
    - generic:
        secret: X9Lb84hZqX6I77ZW2iWFHBhwvMstjNWJL
      type: Generic
    - type: ConfigChange
