apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: grafana:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/grafana-docker.git
      ref: openshift
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
    - github:
        secret: fe2dc366-7186-4caf-be54-dbffdd94153a
      type: GitHub
    - type: ConfigChange
