apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: wordpress-hhvm-app
  name: wordpress-hhvm-app
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: wordpress-hhvm-app:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/openshift-wordpress-hhvm.git
      ref: release
    type: Git
    contextDir: hhvm/
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: hhvm-webserver:latest
        namespace: weepee-registry
    type: Docker
  triggers:
    - github:
        secret: BVi2dtDOAXmZXbNNYYfeZY2jGqTiao6Qp
      type: GitHub
    - generic:
        secret: BVi2dtDOAXmZXbNNYYfeZY2jGqTiao6Qp
      type: Generic
    - type: ConfigChange
