apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: php-phalcon-webserver
  name: php-phalcon-webserver
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: php-phalcon-webserver:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/openshift-apache-php-phalcon.git
      ref: release
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
    - github:
        secret: o74l3qx2GViYtbtPomBG9Ya8qrjlXPeE3
      type: GitHub
    - generic:
        secret: o74l3qx2GViYtbtPomBG9Ya8qrjlXPeE3
      type: Generic
    - type: ConfigChange
