apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: php-webserver
  name: php-webserver
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: php-webserver:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/openshift-apache-php.git
      ref: release
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
    - github:
        secret: xaZW0nvosDTNqs39OKKrln1Cku0n4J4E4
      type: GitHub
    - generic:
        secret: xaZW0nvosDTNqs39OKKrln1Cku0n4J4E4
      type: Generic
    - type: ConfigChange
