apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: wordpress-php-app
  name: wordpress-php-app
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: wordpress-php-app:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/openshift-wordpress-php.git
      ref: release
    type: Git
    contextDir: php/
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: php-webserver:latest
        namespace: weepee-registry
    type: Docker
  triggers:
    - github:
        secret: P+kan+NrlmlehtZp
      type: GitHub
    - generic:
        secret: +9xd21REVWeV5w5R
      type: Generic
    - type: ConfigChange
