apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: wordpress-php-app
  name: wordpress-php-app
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: wordpress-php-app:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/openshift-wordpress-php.git
      ref: release
    type: Git
    contextDir: php/
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: php7-webserver:latest
        namespace: weepee-registry
    type: Docker
  triggers:
    - github:
        secret: G3dnC3WBxQ3oQ1QKKA1r1wMNjsFr8z3QX
      type: GitHub
    - generic:
        secret: G3dnC3WBxQ3oQ1QKKA1r1wMNjsFr8z3QX
      type: Generic
    - type: ConfigChange
