apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: phppgadmin-app
  name: phppgadmin-app
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: phppgadmin-app:latest
  resources: {}
  source:
    git:
      uri: https://github.com/weepee-org/openshift-phppgadmin.git
      ref: release
    type: Git
    contextDir: phpPgAdmin/
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: php-webserver:latest
        namespace: weepee-registry
    type: Docker
  triggers:
    - github:
        secret: vKP4q5bJ8Zb2qxEEnf6nbnYd8J2ZYp6rE
      type: GitHub
    - generic:
        secret: vKP4q5bJ8Zb2qxEEnf6nbnYd8J2ZYp6rE
      type: Generic
    - type: ConfigChange
