apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: asterisk
  name: asterisk
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: asterisk:latest
  resources: {}
  source:
    git:
      uri: git@github.com:weepee-org/wp-alpha-registry.git
      ref: master
    contextDir: asterisk/
    type: Git
    sourceSecret:
      name: weepee-registry
  strategy:
    type: Docker
    dockerStrategy:
      forcePull: true
  triggers:
    - github:
        secret: RQCkhwrMwly0uyTEt9GajfTIReM5LwGkq
      type: GitHub
    - generic:
        secret: RQCkhwrMwly0uyTEt9GajfTIReM5LwGkq
      type: Generic
    - type: ConfigChange
