apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: s3-backup
  name: s3-backup
  namespace: weepee-registry
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s3-backup:latest
  resources: {}
  source:
    git:
      uri: git@github.com:weepee-org/wp-alpha-registry.git
      ref: master
    contextDir: s3-backup/
    type: Git
    sourceSecret:
      name: weepee-registry
  strategy:
    type: Docker
    dockerStrategy:
      forcePull: true
